
import img1 from '../assets/images/imgSA10s.jpg'
import img2 from '../assets/images/i15t.jpg'
import img3 from '../assets/images/xiaominote13.webp'
import img4 from '../assets/images/motorolag54.webp'
import { Product } from '../models/product/Product'

export const response: Product[] = [
    {
        "id": 1,
        "name": 'Samsung A10s',
        "maker": 'Samsung',
        "productWeight": "50 gr",
        "dimensions": "11 x 10 pulgadas",
        "countryOrigin": "China",
        "modelNumber": 134087,
        "color": 'plata',
        "material": "Silicona plastico",
        "partsCant": 4,
        "specialFeatures": "Resistente al agua",
        "componentsIncluded": 'Audifonos, cargador y manual de usuario',
        "urlImg": img1,
        "price": 250,
        "rate": 4,
    },
    {
        "id": 2,
        "name": 'Iphone 15 ProMax',
        "maker": 'Apple',
        "productWeight": "50 gr",
        "dimensions": "11 x 10 pulgadas",
        "countryOrigin": "China",
        "modelNumber": 134087,
        "color": 'plata',
        "material": "Titanium",
        "partsCant": 4,
        "specialFeatures": "Resistente al agua",
        "componentsIncluded": 'cargador y manual de usuario',
        "urlImg": img2,
        "price": 1200,
        "rate": 5,
    },
    {
        "id": 3,
        "name": 'Xiaomi Note 13',
        "maker": 'Xiaomi',
        "productWeight": "50 gr",
        "dimensions": "11 x 10 pulgadas",
        "countryOrigin": "China",
        "modelNumber": 134087,
        "color": 'plata',
        "material": "Silicona plastico",
        "partsCant": 4,
        "specialFeatures": "Resistente al agua",
        "componentsIncluded": 'Audifonos, cargador y manual de usuario',
        "urlImg": img3,
        "price": 700,
        "rate": 3,
    },
    {
        "id": 4,
        "name": 'Motorola G 54',
        "maker": 'Motorola',
        "productWeight": "50 gr",
        "dimensions": "11 x 10 pulgadas",
        "countryOrigin": "China",
        "modelNumber": 134087,
        "color": 'plata',
        "material": "Titanium",
        "partsCant": 4,
        "specialFeatures": "Resistente al agua",
        "componentsIncluded": 'cargador y manual de usuario',
        "urlImg": img4,
        "price": 1000,
        "rate": 4,
    },
]
